# أساسيات بايتورتش للديب ليرننق

- نوشن: https://www.notion.so/19ac66537749806cacd6db749955e8c7?v=19ac6653774981bf9d0e000cda83898f&pvs=4
- 

## Setting Up PyTorch

In [26]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(f"Torch version is: {torch.__version__ }")

cuda0 = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {cuda0}")

if cuda0 == "cuda":
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Capability: {torch.cuda.get_device_capability(0)}")
    print(f"Total Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9} GB")
    print(f"Memory Allocated: {torch.cuda.memory_allocated(0) / 1e9} GB")
    print(f"Memory Cached: {torch.cuda.memory_reserved(0) / 1e9} GB")

Torch version is: 2.5.1+cu118
Using device: cuda
GPU Name: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA Capability: (8, 9)
Total Memory: 8.585216 GB
Memory Allocated: 3.584e-06 GB
Memory Cached: 0.002097152 GB


## Tensors, what Tensors?

In [27]:
## PyTorch Fundementals for DL by https://github.com/mrdbourke , you can also find our Notion notebook on:
# https://www.notion.so/19ac66537749806cacd6db749955e8c7?v=19ac6653774981bf9d0e000cda83898f&pvs=4
# feel free to tag along and learn with us!


# Example tensor
tensor = torch.tensor([1.0, 2.0, 3.0])

# Move tensor to the GPU if available
tensor = tensor.to(cuda0)
print(tensor)

tensor([1., 2., 3.], device='cuda:0')


مقدمة: ماهو تنسور؟ مازلت تتذكر فيه من النوشن بووك؟
خليني نذكرك: تنسور هو طريقة تمثيل الداتا

وتوا حنديرو عمليات الأساسية على كل انواع التنسورز
1. سكيلر
2. متجه
3. مصفوفة

صفات التنسور:

شكله tensor.shape

حجمه tensor.size

tensor.ndim أبعاده




### Scalar Tensor

In [28]:
# Tensor: Scalar

scalar = torch.tensor([7])
print(scalar)
print(f" Scalar shape: {scalar.shape}") #shape
print(f" Scalar Size: {scalar.size}") #size
print(f" Number of Dimensions: {scalar.ndim}") #ndim

newScalar = torch.tensor(7, device = cuda0) #on GPU :)
print(f" Scalar items: {scalar.item()}")
print(f" Scalar datatype: {scalar.dtype}")
print(f" Scalar on device: {scalar.device}") # do , device = device , we initialized it earlier to have a cuda
print(f" newScalar on device: {newScalar.device}") # do , device = device , we initialized it earlier to have a cuda


tensor([7])
 Scalar shape: torch.Size([1])
 Scalar Size: <built-in method size of Tensor object at 0x000002038F22FCC0>
 Number of Dimensions: 1
 Scalar items: 7
 Scalar datatype: torch.int64
 Scalar on device: cpu
 newScalar on device: cuda:0


### Vector Tensor

In [29]:
# Tensor: Vector متجه
cpu_vector = torch.tensor([7, 7])
gpu_vector = cpu_vector.to(cuda0)

print(f"CPU Vector: {cpu_vector}")
print(f"GPU Vector: {gpu_vector}\n")

print(f"CPU Vector Device: {cpu_vector.device}")
print(f"GPU Vector Device: {gpu_vector.device}\n")

print(f"CPU Vector Shape: {cpu_vector.shape}")
print(f"GPU Vector Shape: {gpu_vector.shape}\n")

print(f"CPU Vector Datatype: {cpu_vector.dtype}") #defualt int64
print(f"GPU Vector Datatype: {gpu_vector.dtype}\n")

print(f"CPU Vector Size: {cpu_vector.size()}")
print(f"GPU Vector Size: {gpu_vector.size()}\n")

print(f"CPU Vector Dimension: {cpu_vector.dim()}")
print(f"GPU Vector Dimension: {gpu_vector.dim()}\n")

print(f"CPU Vector nDimension: {cpu_vector.ndim}")
print(f"GPU Vector nDimension: {gpu_vector.ndim}\n")

CPU Vector: tensor([7, 7])
GPU Vector: tensor([7, 7], device='cuda:0')

CPU Vector Device: cpu
GPU Vector Device: cuda:0

CPU Vector Shape: torch.Size([2])
GPU Vector Shape: torch.Size([2])

CPU Vector Datatype: torch.int64
GPU Vector Datatype: torch.int64

CPU Vector Size: torch.Size([2])
GPU Vector Size: torch.Size([2])

CPU Vector Dimension: 1
GPU Vector Dimension: 1

CPU Vector nDimension: 1
GPU Vector nDimension: 1



### MATRIX Vector

In [30]:
#MATRIX

cpu_MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
gpu_MATRIX = torch.tensor([[7, 8],
                       [9, 10]], device = cuda0)

print(f"CPU MATRIX Shape: {cpu_MATRIX.shape}")
print(f"GPU MATRIX Shape: {gpu_MATRIX.shape}\n")

print(f"CPU MATRIX size: {cpu_MATRIX.size}")
print(f"GPU MATRIX size: {gpu_MATRIX.size}\n")

print(f"CPU MATRIX datatype: {cpu_MATRIX.dtype}")
print(f"GPU MATRIX datatype: {gpu_MATRIX.dtype}\n")

print(f"CPU MATRIX dimensions: {cpu_MATRIX.dim()}")
print(f"GPU MATRIX dimensions: {gpu_MATRIX.dim()}\n")

print(f"CPU MAtrix nDimensions: {cpu_MATRIX.ndim}")
print(f"GPU MAtrix nDimensions: {gpu_MATRIX.ndim}\n")

print(f"CPU MATRIX device: {cpu_MATRIX.device}")
print(f"GPU MATRIX device: {gpu_MATRIX.device}\n")

CPU MATRIX Shape: torch.Size([2, 2])
GPU MATRIX Shape: torch.Size([2, 2])

CPU MATRIX size: <built-in method size of Tensor object at 0x000002038F24E310>
GPU MATRIX size: <built-in method size of Tensor object at 0x000002038F00B270>

CPU MATRIX datatype: torch.int64
GPU MATRIX datatype: torch.int64

CPU MATRIX dimensions: 2
GPU MATRIX dimensions: 2

CPU MAtrix nDimensions: 2
GPU MAtrix nDimensions: 2

CPU MATRIX device: cpu
GPU MATRIX device: cuda:0



### Tensor tensor

In [31]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]], device = cuda0)
TENSOR.ndim #ndim = number of dimensions

3

## Generating Tensors

### Random Tensors

In [32]:
random_cpu_tensor = torch.rand(10, 2, 2)
random_gpu_tensor = random_cpu_tensor.to(cuda0)

print(f"CPU Random Tensor: \n{random_cpu_tensor}\n")
print(f"GPU Random Tensor: \n{random_gpu_tensor}\n")

CPU Random Tensor: 
tensor([[[0.5622, 0.4116],
         [0.5736, 0.8218]],

        [[0.8165, 0.4656],
         [0.8148, 0.6257]],

        [[0.0344, 0.5809],
         [0.9565, 0.7587]],

        [[0.1610, 0.4673],
         [0.6245, 0.6116]],

        [[0.6286, 0.6669],
         [0.1803, 0.5619]],

        [[0.9868, 0.8454],
         [0.8841, 0.6960]],

        [[0.2774, 0.0473],
         [0.7853, 0.1444]],

        [[0.4443, 0.5686],
         [0.6492, 0.3484]],

        [[0.6636, 0.0972],
         [0.2026, 0.8807]],

        [[0.3339, 0.3142],
         [0.4543, 0.0762]]])

GPU Random Tensor: 
tensor([[[0.5622, 0.4116],
         [0.5736, 0.8218]],

        [[0.8165, 0.4656],
         [0.8148, 0.6257]],

        [[0.0344, 0.5809],
         [0.9565, 0.7587]],

        [[0.1610, 0.4673],
         [0.6245, 0.6116]],

        [[0.6286, 0.6669],
         [0.1803, 0.5619]],

        [[0.9868, 0.8454],
         [0.8841, 0.6960]],

        [[0.2774, 0.0473],
         [0.7853, 0.1444]],

       

### Create a random tensor similar to image tensor

In [33]:
cpu_img_tensor = torch.rand(size=(244,244,3))
cpu_img_tensor.shape, cpu_img_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Tensors in Zeros and Ones

In [34]:
rand_cpu_TENSOR = torch.rand(5, 5, 5)
rand_gpu_TENSOR = torch.rand(5, 5, 5, device = cuda0)

print(rand_cpu_TENSOR)
print(rand_gpu_TENSOR)

print(f"rand CPU Tensor size: \n {rand_cpu_TENSOR.size()}\n")
print(f"rand GPU Tensor size: \n {rand_gpu_TENSOR.size()}\n")

print(f"rand CPU Tensor shape: \n {rand_cpu_TENSOR.shape}\n")
print(f"rand GPU Tensor shape: \n {rand_gpu_TENSOR.shape}\n")

print(f"rand CPU Tensor nDimensions: \n {rand_cpu_TENSOR.ndim}\n")
print(f"rand GPU Tensor nDimensions: \n {rand_gpu_TENSOR.ndim}\n")

mult = torch.mul(rand_cpu_TENSOR, rand_cpu_TENSOR) #can't multiply tensosrs on different devices
#and in different dimensions
print(f"Multiply random CPU tensor with random GPU tensor, \nresult:\n{mult}\n")


tensor([[[0.1273, 0.2793, 0.0280, 0.4550, 0.6594],
         [0.7914, 0.0734, 0.2115, 0.2421, 0.8224],
         [0.5137, 0.6655, 0.3164, 0.5670, 0.7936],
         [0.5205, 0.7854, 0.3050, 0.0476, 0.4286],
         [0.7231, 0.7995, 0.5213, 0.5170, 0.4910]],

        [[0.8778, 0.1518, 0.5896, 0.6126, 0.3451],
         [0.9404, 0.0570, 0.2876, 0.9616, 0.8478],
         [0.8833, 0.5802, 0.1597, 0.7284, 0.5452],
         [0.0974, 0.1001, 0.9864, 0.3888, 0.6594],
         [0.2107, 0.3714, 0.8695, 0.2428, 0.2407]],

        [[0.5560, 0.1503, 0.5724, 0.5835, 0.5845],
         [0.6849, 0.6989, 0.5027, 0.5485, 0.0170],
         [0.4222, 0.6897, 0.7067, 0.5147, 0.2698],
         [0.6923, 0.2527, 0.7509, 0.1334, 0.8540],
         [0.1541, 0.2395, 0.5380, 0.2964, 0.6073]],

        [[0.0012, 0.5028, 0.1972, 0.6776, 0.5822],
         [0.0585, 0.2196, 0.4931, 0.1278, 0.0930],
         [0.1269, 0.5565, 0.4606, 0.8920, 0.0436],
         [0.0193, 0.6907, 0.8510, 0.4378, 0.1691],
         [0.0392, 0.1595,

### Creating a range of tensors and tensors-like

In [35]:
print(torch.arange(start=0,step=1,dtype=torch.int64,end=12))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Tensors Manipulation

In [36]:
cpu_vector = torch.tensor([7, 7])

print(f"Mutiply: {cpu_vector*10}") #70
print(f"Add: {cpu_vector+100}") #107
print(f"Subtract: {cpu_vector-7}") #0
print(f"Divide: {cpu_vector/7}") #1
print(f"Exponent: {cpu_vector**2}") #49
print(f"Modulus: {cpu_vector%5}") #2
print(f"Dot product: {torch.dot(cpu_vector, cpu_vector)}") #49
#print(f"Cross product: {torch.cross(cpu_vector, cpu_vector)}") #0

Mutiply: tensor([70, 70])
Add: tensor([107, 107])
Subtract: tensor([0, 0])
Divide: tensor([1., 1.])
Exponent: tensor([49, 49])
Modulus: tensor([2, 2])
Dot product: 98


# Torch Ops

## Matrices Multiplication

Multiplying 2 matrices:
- Element wise multiplication
- Matrix mult which is called dot product

Feel free to go over the basics of matrices and Linear algebra

In [37]:
temp_tensor = torch.tensor([1, 2, 3])
print(temp_tensor)

print(temp_tensor, "*", temp_tensor ,"=" , temp_tensor*temp_tensor)

print("torch.mult(temp_tensor, temp_tensor) = ", torch.matmul(temp_tensor, temp_tensor))



tensor([1, 2, 3])
tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
torch.mult(temp_tensor, temp_tensor) =  tensor(14)


#### what is the difference between the 2 multiplications?
dot product
and
element multiplication

Lets multiply the matrices of different shapes using transpose!

In [38]:
matrix_2x3 = torch.tensor([[1, 2, 3],
                           [4, 5, 6]])

matrix_3x2 = torch.tensor([[7, 8],
                           [9, 10],
                           [11, 12]])

# Transpose the matrices
matrix_2x3_T = matrix_2x3.T
matrix_3x2_T = matrix_3x2.T

print(f"Original Matrix 2x3:\n{matrix_2x3}\n")
print(f"Transposed Matrix 2x3 (3x2):\n{matrix_2x3_T}\n")

print(f"Original Matrix 3x2:\n{matrix_3x2}\n")
print(f"Transposed Matrix 3x2 (2x3):\n{matrix_3x2_T}\n")

Original Matrix 2x3:
tensor([[1, 2, 3],
        [4, 5, 6]])

Transposed Matrix 2x3 (3x2):
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Original Matrix 3x2:
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

Transposed Matrix 3x2 (2x3):
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])



In [39]:
#                                         2             2     
print("Hello Errors: \n", torch.mm(matrix_2x3, matrix_3x2))
print("Hello Errors: \n", torch.mm(matrix_2x3.T, matrix_2x3))

Hello Errors: 
 tensor([[ 58,  64],
        [139, 154]])
Hello Errors: 
 tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])


In [40]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])

tensor_b = torch.tensor([[5, 6, 7],
                         [8, 9, 10]])

# Tensors Aggregation
- Min
- Max
- Mean
- Sum


In [48]:
temp_tensor = torch.tensor([1,2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100])
print("Minimum is: ",torch.min(temp_tensor),"\nlocation: " ,torch.argmin(temp_tensor)) # -> 1
print("Maximum is: ", torch.max(temp_tensor), "\nlocation: ", torch.argmax(temp_tensor),"\n") # -> 100
print("Mean is: ",torch.mean(temp_tensor.type(torch.float32)), "\nnotice that we needed to convert it to float get the mean") # -> 31.3158
print("of type: ",temp_tensor.type()) # -> torch.LongTensor
print(temp_tensor.type(torch.float32)) # -> torch.FloatTensor

Minimum is:  tensor(1) 
location:  tensor(0)
Maximum is:  tensor(100) 
location:  tensor(18) 

Mean is:  tensor(31.3158) 
notice that we needed to convert it to float get the mean
of type:  torch.LongTensor
tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  20.,  30.,
         40.,  50.,  60.,  70.,  80.,  90., 100.])


In [49]:
print(torch.sum(temp_tensor)) # -> 595

tensor(595)


## Tensor Sculpture :)
- Reshaping
- Stacking
- Squeezing / unSqueezing
- View
- Stacking , Vertical Stacking & Horizontal Sacking
- Permute: Swap Dimensions in a certain way


### Reshaping Tensor

In [50]:
x = torch.arange(0,100,1)
x
x.reshape(5,20)
x.size()
#x.shape

torch.Size([100])

### Stacking Tensors

In [51]:
# Generate 5 random matrices
random_matrices = [torch.rand(2, 3) for _ in range(5)]

# Stack matrices horizontally
horizontal_stack = torch.hstack(random_matrices)

# Stack matrices vertically
vertical_stack = torch.vstack(random_matrices)

print("Generated 5 Random Matrices:")
for i, matrix in enumerate(random_matrices):
    print(f"Matrix {i+1}:\n{matrix}\n")

print("Horizontal Stack of the 5 Random Matrices:")
print(horizontal_stack)

print("\nVertical Stack of the 5 Random Matrices:")
print(vertical_stack)

print("\nUsing .Stack function with dim=0:\n") #at position 0
print(torch.stack(random_matrices, dim=0)) # -> 5x2x3

print("\nUsing .Stack function with dim=1:\n") #at position 1
print(torch.stack(random_matrices, dim=1))# -> 2x5x3

Generated 5 Random Matrices:
Matrix 1:
tensor([[0.5619, 0.7763, 0.6536],
        [0.4909, 0.7916, 0.4193]])

Matrix 2:
tensor([[0.6917, 0.3214, 0.1560],
        [0.0827, 0.3290, 0.1687]])

Matrix 3:
tensor([[0.8844, 0.6342, 0.8976],
        [0.3718, 0.0898, 0.8400]])

Matrix 4:
tensor([[0.2083, 0.9601, 0.3186],
        [0.5770, 0.5245, 0.1595]])

Matrix 5:
tensor([[0.5237, 0.7494, 0.9080],
        [0.2149, 0.4734, 0.4034]])

Horizontal Stack of the 5 Random Matrices:
tensor([[0.5619, 0.7763, 0.6536, 0.6917, 0.3214, 0.1560, 0.8844, 0.6342, 0.8976,
         0.2083, 0.9601, 0.3186, 0.5237, 0.7494, 0.9080],
        [0.4909, 0.7916, 0.4193, 0.0827, 0.3290, 0.1687, 0.3718, 0.0898, 0.8400,
         0.5770, 0.5245, 0.1595, 0.2149, 0.4734, 0.4034]])

Vertical Stack of the 5 Random Matrices:
tensor([[0.5619, 0.7763, 0.6536],
        [0.4909, 0.7916, 0.4193],
        [0.6917, 0.3214, 0.1560],
        [0.0827, 0.3290, 0.1687],
        [0.8844, 0.6342, 0.8976],
        [0.3718, 0.0898, 0.8400],
   

### Squeezing Tensors

In [52]:
# Squeezing
# Remove single-dimensional entries from the shape of 'TENSOR'
squeezed_tensor = TENSOR.squeeze()
print("\nSqueezed Tensor:\n", squeezed_tensor)

# UnSqueezing
# Add a single-dimensional entry to the shape of 'squeezed_tensor'
unsqueezed_tensor = squeezed_tensor.unsqueeze(0)
print("\nUnSqueezed Tensor:\n", unsqueezed_tensor)


# Stacking, Vertical Stacking & Horizontal Stacking
# Stack 'cpu_vector' vertically and horizontally
vertical_stack = torch.vstack((cpu_vector, cpu_vector))
horizontal_stack = torch.hstack((cpu_vector, cpu_vector))
print("\nVertical Stack:\n", vertical_stack)
print("\nHorizontal Stack:\n", horizontal_stack)




Squeezed Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')

UnSqueezed Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], device='cuda:0')

Vertical Stack:
 tensor([[7, 7],
        [7, 7]])

Horizontal Stack:
 tensor([7, 7, 7, 7])


### View Tensor

In [71]:

# View
# Change the view of 'reshaped_tensor' to a 2x5x10 tensor
reshaped_tensor = torch.arange(0, 100)
viewed_tensor = reshaped_tensor.view(2, 5, 10) # -> 2 Matrices, 5 Rows and 10 Columns each
print("\nViewed Tensor (2x5x10):\n", viewed_tensor)


Viewed Tensor (2x5x10):
 tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])


### Permute Tensor

In [54]:
# Permute: Swap Dimensions in a certain way
# Change the order of dimensions of 'cpu_img_tensor'
permuted_tensor = cpu_img_tensor.permute(2, 0, 1)
print("\nPermuted Tensor (Swapped Dimensions):\n", permuted_tensor)
# Used with images usually :)


Permuted Tensor (Swapped Dimensions):
 tensor([[[9.0245e-01, 6.9792e-01, 8.5409e-01,  ..., 5.1611e-01,
          6.9189e-01, 2.5989e-01],
         [2.2769e-01, 4.3870e-01, 3.3006e-01,  ..., 1.0962e-01,
          5.9821e-01, 6.2123e-01],
         [8.1056e-01, 9.3157e-01, 5.2493e-01,  ..., 5.3297e-02,
          1.1896e-01, 1.6134e-01],
         ...,
         [4.3832e-01, 7.6814e-01, 7.4798e-01,  ..., 2.6368e-01,
          3.5422e-01, 5.6247e-01],
         [6.5018e-01, 6.2464e-01, 4.7184e-01,  ..., 9.1836e-01,
          1.7395e-01, 7.9691e-01],
         [5.0237e-02, 1.8236e-01, 4.3364e-01,  ..., 6.4957e-01,
          1.5362e-01, 5.0605e-01]],

        [[2.9680e-01, 3.7585e-01, 4.6269e-01,  ..., 8.1825e-01,
          7.4324e-01, 7.7889e-01],
         [3.3540e-01, 8.7558e-01, 3.6492e-02,  ..., 7.8436e-01,
          1.0729e-01, 7.5248e-01],
         [4.0639e-01, 4.5671e-01, 2.9442e-01,  ..., 2.0778e-01,
          5.9588e-01, 3.6297e-01],
         ...,
         [7.6230e-01, 1.0581e-01, 1.305

# PyTorch tensors & NumPy

PyTorch can intreact with NumPy, for an example your data is in NumPy, and to do DL and ML using PyTorch -> `torch.from_numpy(ndarray)`
